# Generated by Django 4.1.3 on 2024-02-20 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledBridgeModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Справочник моделей управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='DrivingBridgeModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Справочник моделей ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='EngineModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Справочник моделей двигателей',
            },
        ),
        migrations.CreateModel(
            name='FailureNodeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование узла')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Справочник узлов отказа',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=75, unique=True, verbose_name='Зав. № машины')),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № двигателя')),
                ('transmission_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Зав. № трансмиссии')),
                ('driving_bridge_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № ведущего моста')),
                ('controlled_bridge_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № управляемого моста')),
                ('delivery_contract', models.CharField(blank=True, max_length=250, null=True, verbose_name='Договор поставки №, дата')),
                ('date_of_shipment', models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(blank=True, max_length=250, null=True, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес поставки (эксплуатации)')),
                ('complete_set', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_machine', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('controlled_bridge_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_bridge_model', to='service.controlledbridgemodelreference', verbose_name='Модель управляемого моста')),
                ('driving_bridge_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driving_bridge_model', to='service.drivingbridgemodelreference', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_model', to='service.enginemodelreference', verbose_name='Модель двигателя')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='MachineModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Справочник моделей машин',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrganisationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уполномоченная в ТО организация',
                'verbose_name_plural': 'Справочник уполномоченных в ТО организаций',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethodReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование узла')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Справочник способов восстановления',
            },
        ),
        migrations.CreateModel(
            name='TransmissionModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Справочник моделей трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='TypeOfMaintenanceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Вид ТО')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид технического обслуживания',
                'verbose_name_plural': 'Справочник видов ТО',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_maintenance', models.DateTimeField(auto_created=True, verbose_name='Дата проведения ТО')),
                ('operating_time', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machine', to='service.machine', verbose_name='Машина')),
                ('type_of_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_maintenance', to='service.typeofmaintenancereference', verbose_name='Вид технического обслуживания')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_model', to='service.machinemodelreference', verbose_name='Модель машины'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_company', to=settings.AUTH_USER_MODEL, verbose_name='Cервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='service.transmissionmodelreference', verbose_name='Модель трансмиссии'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateTimeField(blank=True, null=True, verbose_name='Дата отказа')),
                ('operating_time', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Наработка, м/час')),
                ('failure_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание отказа')),
                ('parts_used', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Используемые запасные части')),
                ('date_of_restoration', models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('equipment_downtime', models.IntegerField(default=0, verbose_name='Время простоя техники (Часов)')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_node', to='service.failurenodereference', verbose_name='Узел отказа')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='service.machine', verbose_name='Машина')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_method', to='service.recoverymethodreference', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
